blank_issues_enabled: false   # hides the default "Open a blank issue" option

contact_links:
  - name: â“ Questions / Help
    url: https://github.com/vikhulei/TeachLearnFront/issues
    about: Please ask questions here if it's not a task/bug.
